# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubu" do |ubu|
     ubu.vm.box = "ubuntu/bionic64"
     #vagrant plugin install vagrant-disksize
     ubu.disksize.size = "20GB"
     ubu.vm.network  "private_network", ip: "192.168.10.2"
     ubu.vm.network  "forwarded_port", guest: 80, host: 9999, auto_correct: true 
     ubu.vm.network  "forwarded_port", guest: 22, host: 2222, auto_correct: true 
     ubu.vm.network  "forwarded_port", guest: 443, host: 9989, auto_correct: true
     ubu.vm.network  "forwarded_port", guest: 8080, host: 9998, auto_correct: true
     ubu.vm.network  "forwarded_port", guest: 8443, host: 8998, auto_correct: true
     ubu.vm.provider "virtualbox" do |vb|
       vb.name = "ubuntu1804"
       vb.memory = "1024"
       #vb.customize ["modifyhd", :id, "--resize", "20480"]
     end
   
  end

  # Disable automatic box update checking.
   config.vm.box_check_update = false
 
end
Vagrant.configure("2") do |config|
  config.vm.define "cen" do |cen|
  cen.vm.box = "centos/7" 
     cen.disksize.size = "20GB"
     cen.vm.network  "private_network", ip: "192.168.10.3"
     cen.vm.provider "virtualbox" do |vb|
       vb.name = "centos7"
       vb.memory = "1024"
       #vb.customize ["modifyhd", :id, "--resize", "20480"]
     end
  end
  

  # Disable automatic box update checking.
   config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
